language: generic
#my-first-app
services:
  - docker
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "my-first-app"
  env: "Myfirstapp-env-1"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  bucket_name: "myfirstapp-bucket1"
  bucket_path: "docker"

  on:
    branch: "master"
